---

- name: Windows | Install puppet-agent from Puppetlabs reposiroty
  win_package:
    path: http://downloads.puppetlabs.com/windows/puppet{{ puppet_version }}/puppet-agent-x64-latest.msi
    product_id: Puppet Agent (64-bit)
    creates_service: puppet
    state: present

- name: Windows | Puppet-agent service
  win_service:
    name: puppet
    start_mode: "{{ puppet_agent_service_enable }}"
    state: started
    state: "{{ puppet_agent_service_ensure }}"
